
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#  Ace




Card.create(value: 'AS', number: 'A', suit: 'spade.png')
Card.create(value: 'AC', number: 'A', suit: 'club.png')
Card.create(value: 'AD', number: 'A', suit: 'diamond.png')
Card.create(value: 'AH', number: 'A', suit: 'heart.png')

# 2
Card.create(value: '2S', number: '2', suit: 'spade.png')
Card.create(value: '2C', number: '2', suit: 'club.png')
Card.create(value: '2D', number: '2', suit: 'diamond.png')
Card.create(value: '2H', number: '2', suit: 'heart.png')

# 3

Card.create(value: '3S', number: '3', suit: 'spade.png')
Card.create(value: '3C', number: '3', suit: 'club.png')
Card.create(value: '3D', number: '3', suit: 'diamond.png')
Card.create(value: '3H', number: '3', suit: 'heart.png')

# 4

Card.create(value: '4S', number: '4', suit: 'spade.png')
Card.create(value: '4C', number: '4', suit: 'club.png')
Card.create(value: '4D', number: '4', suit: 'diamond.png')
Card.create(value: '4H', number: '4', suit: 'heart.png')

# 5

Card.create(value: '5S', number: '5', suit: 'spade.png')
Card.create(value: '5C', number: '5', suit: 'club.png')
Card.create(value: '5D', number: '5', suit: 'diamond.png')
Card.create(value: '5H', number: '5', suit: 'heart.png')

# 6

Card.create(value: '6S', number: '6', suit: 'spade.png')
Card.create(value: '6C', number: '6', suit: 'club.png')
Card.create(value: '6D', number: '6', suit: 'diamond.png')
Card.create(value: '6H', number: '6', suit: 'heart.png')

# 7

Card.create(value: '7S', number: '7', suit: 'spade.png')
Card.create(value: '7C', number: '7', suit: 'club.png')
Card.create(value: '7D', number: '7', suit: 'diamond.png')
Card.create(value: '7H', number: '7', suit: 'heart.png')


# 8

Card.create(value: '8S', number: '8', suit: 'spade.png')
Card.create(value: '8C', number: '8', suit: 'club.png')
Card.create(value: '8D', number: '8', suit: 'diamond.png')
Card.create(value: '8H', number: '8', suit: 'heart.png')

# 9

Card.create(value: '9S', number: '9', suit: 'spade.png')
Card.create(value: '9C', number: '9', suit: 'club.png')
Card.create(value: '9D', number: '9', suit: 'diamond.png')
Card.create(value: '9H', number: '9', suit: 'heart.png')

# 10

Card.create(value: '10S', number: '10', suit: 'spade.png')
Card.create(value: '10C', number: '10', suit: 'club.png')
Card.create(value: '10D', number: '10', suit: 'diamond.png')
Card.create(value: '10H', number: '10', suit: 'heart.png')

# J

Card.create(value: 'JS', number: 'J', suit: 'spade.png')
Card.create(value: 'JC', number: 'J', suit: 'club.png')
Card.create(value: 'JD', number: 'J', suit: 'diamond.png')
Card.create(value: 'JH', number: 'J', suit: 'heart.png')

# Q

Card.create(value: 'QS', number: 'Q', suit: 'spade.png')
Card.create(value: 'QC', number: 'Q', suit: 'club.png')
Card.create(value: 'QD', number: 'Q', suit: 'diamond.png')
Card.create(value: 'QH', number: 'Q', suit: 'heart.png')

# K

Card.create(value: 'KS', number: 'K', suit: 'spade.png')
Card.create(value: 'KC', number: 'K', suit: 'club.png')
Card.create(value: 'KD', number: 'K', suit: 'diamond.png')
Card.create(value: 'KH', number: 'K', suit: 'heart.png')



OnlineSite.create(name: "I Don't Play Poker Online", downcased_name: "i don't play poker online")
OnlineSite.create(name: "888 Poker", downcased_name: "888 poker")
OnlineSite.create(name: "888 Poker.es", downcased_name: "888 poker.es")
OnlineSite.create(name: "ActiveGames.it", downcased_name: "activegames.it")
OnlineSite.create(name: "Adda52", downcased_name: " 	adda52")
OnlineSite.create(name: "Adjarabet", downcased_name: "adjarabet")
OnlineSite.create(name: "All American", downcased_name: "all american")
OnlineSite.create(name: "Americas Cardroom", downcased_name: "americas cardroom")
OnlineSite.create(name: "Bet 365 Poker", downcased_name: "bet 365 poker")
OnlineSite.create(name: "BetOnline Poker", downcased_name: "betonline poker")
OnlineSite.create(name: "Bettiamoci.it", downcased_name: "bettiamoci.it")
OnlineSite.create(name: "BetVictor", downcased_name: " 	betvictor")
OnlineSite.create(name: "Black Chip Poker", downcased_name: "black chip poker")
OnlineSite.create(name: "Bodog Poker", downcased_name: "bodog poker")
OnlineSite.create(name: "Bovada Poker", downcased_name: "bovada poker")
OnlineSite.create(name: "Bwin", downcased_name: "bwin")
OnlineSite.create(name: "Cake Poker", downcased_name: "cake poker")
OnlineSite.create(name: "Carbon Poker", downcased_name: "carbon poker")
OnlineSite.create(name: "Chico", downcased_name: "chico")
OnlineSite.create(name: "Chilli Poker", downcased_name: "chilli poker")
OnlineSite.create(name: "Delaware Poker", downcased_name: "delaware poker")
OnlineSite.create(name: "Dollaro", downcased_name: "dollaro")
OnlineSite.create(name: "Enet", downcased_name: "enet")
OnlineSite.create(name: "Equity", downcased_name: "equity")
OnlineSite.create(name: "Europe Bet", downcased_name: "europe bet")
OnlineSite.create(name: "Everest Poker", downcased_name: "everest poker")
OnlineSite.create(name: "Everleaf Poker", downcased_name: "everleaf poker")
OnlineSite.create(name: "First Fidelity", downcased_name: " 	first fidelity")
OnlineSite.create(name: "Full Tilt Poker", downcased_name: "full tilt poker")
OnlineSite.create(name: "Hero Poker", downcased_name: "hero poker")
OnlineSite.create(name: "International", downcased_name: "international")
OnlineSite.create(name: "International.ca", downcased_name: "international.ca")
OnlineSite.create(name: "International.es", downcased_name: "international.es")
OnlineSite.create(name: "iPoker", downcased_name: "ipoker")
OnlineSite.create(name: "iPoker.es", downcased_name: "ipoker.es")
OnlineSite.create(name: "iPoker.fr", downcased_name: "ipoker.fr")
OnlineSite.create(name: "iPoker.it", downcased_name: "ipoker.it")
OnlineSite.create(name: "League", downcased_name: "league")
OnlineSite.create(name: "Live Holdem Poker(mobile)", downcased_name: "live holdem poker (mobile)")
OnlineSite.create(name: "Lock Poker", downcased_name: "lock poker")
OnlineSite.create(name: "Merge", downcased_name: "merge")
OnlineSite.create(name: "Microgaming.es", downcased_name: "microgaming.es")
OnlineSite.create(name: "Mobile Poker Club", downcased_name: "mobile poker club")
OnlineSite.create(name: "MPN", downcased_name: "mpn")
OnlineSite.create(name: "MyPok.fr", downcased_name: "mypok.fr")
OnlineSite.create(name: "Ongame", downcased_name: "ongame")
OnlineSite.create(name: "Ongame.fr", downcased_name: "ongame.fr")
OnlineSite.create(name: "Paddy Power Poker", downcased_name: "paddy power poker")
OnlineSite.create(name: "Party Borgata (NJ)", downcased_name: "party borgata (nj)")
OnlineSite.create(name: "Party Poker", downcased_name: "party poker")
OnlineSite.create(name: "Party Poker.fr", downcased_name: " 	party poker.fr")
OnlineSite.create(name: "Party Poker.it", downcased_name: "party poker.it")
OnlineSite.create(name: "Party Poker.es", downcased_name: "party poker.es")
OnlineSite.create(name: "PeoplesNetwork.it", downcased_name: "peoplesnetwork.it")
OnlineSite.create(name: "PKR", downcased_name: "pkr")
OnlineSite.create(name: "PKR.it", downcased_name: "pkr.it")
OnlineSite.create(name: "PlayersOnly Poker", downcased_name: "playersonly poker")
OnlineSite.create(name: "Pocket Rockets", downcased_name: "pocket rockets")
OnlineSite.create(name: "Poker (Mobile)", downcased_name: "poker (mobile)")
OnlineSite.create(name: "Poker Stars", downcased_name: "poker stars")
OnlineSite.create(name: "Pokerist (Mobile)", downcased_name: "pokerist (mobile)")
OnlineSite.create(name: "PokerStars", downcased_name: "pokerstars")
OnlineSite.create(name: "PokerStars.es", downcased_name: "pokerstars.es")
OnlineSite.create(name: "PokerStars.fr", downcased_name: "pokerstars.fr")
OnlineSite.create(name: "PokerStars.it", downcased_name: "pokerstars.it")
OnlineSite.create(name: "PRK.fr", downcased_name: "prk.fr")
OnlineSite.create(name: "Ray.fi", downcased_name: "ray.fi")
OnlineSite.create(name: "Revolution", downcased_name: "revolution")
OnlineSite.create(name: "SealswithClubs", downcased_name: "sealswithclubs")
OnlineSite.create(name: "SIA Poker", downcased_name: "sia poker")
OnlineSite.create(name: "Skypoker", downcased_name: "skypoker")
OnlineSite.create(name: "Sportsbetting", downcased_name: "sportsbetting")
OnlineSite.create(name: "Sportsbook Poker", downcased_name: "sportsbook poker")
OnlineSite.create(name: "Svenska Spel", downcased_name: "svenska spel")
OnlineSite.create(name: "Texas Holdem Poker(mobile)", downcased_name: "texas holdem poker(mobile)")
OnlineSite.create(name: "The Hive", downcased_name: "the hive")
OnlineSite.create(name: "Titan Poker", downcased_name: "titan poker")
OnlineSite.create(name: "TX Poker (Mobile)", downcased_name: "tx poker (mobile)")
OnlineSite.create(name: "Ultima", downcased_name: "ultima ")
OnlineSite.create(name: "Ultimate ", downcased_name: "ultimate")
OnlineSite.create(name: "Unibet", downcased_name: "unibet")
OnlineSite.create(name: "VIP Poker (Mobile)", downcased_name: "vip poker (mobile)")
OnlineSite.create(name: "William Hill", downcased_name: "william hill")
OnlineSite.create(name: "Win2Day", downcased_name: "win2day")
OnlineSite.create(name: "Winamax.fr", downcased_name: "winamax.fr")
OnlineSite.create(name: "Winning", downcased_name: "winning")
OnlineSite.create(name: "World Series of Poker", downcased_name: "world series of poker")
OnlineSite.create(name: "WSOP (Mobile)", downcased_name: "wsop (mobile)")
OnlineSite.create(name: "WSOP (Nevada)", downcased_name: "wsop (nevada)")

OnlineSite.create(name: "WSOP (NJ)", downcased_name: "wsop (nj)")
OnlineSite.create(name: "Xbox Live Poker", downcased_name: "xbox live poker")
OnlineSite.create(name: "Zynga Poker (Mobile)", downcased_name: "zynga poker (mobile)")


AdminResetPassword.create(:name=>"Vir9&abCk!",:password=>"Bmd!!84aJR*")


Casino.create(name: "I Don't Play Poker in Casino's", downcased_name: "i don't play poker in casino's")
Casino.create(name: "Atlantis Resort & Casino", downcased_name: "atlantis resort & casino")
Casino.create(name: "Aviation Club de France", downcased_name: "aviation club de france")
Casino.create(name: "Baccarat Casino", downcased_name: "baccarat casino")
Casino.create(name: "Bay 101", downcased_name: "bay 101")
Casino.create(name: "Bear Claw Casino", downcased_name: "bear claw casino")
Casino.create(name: "Beau Rivage Hotel & Casino", downcased_name: "beau rivage hotel & casino")
Casino.create(name: "Bellagio", downcased_name: "bellagio")
Casino.create(name: "Bicycle Casino", downcased_name: "bicycle casino")
Casino.create(name: "Binion's", downcased_name: "binion's")
Casino.create(name: "Boomtown Casino", downcased_name: "boomtown casino")
Casino.create(name: "Borgata", downcased_name: "borgata")
Casino.create(name: "Boulevard Casino", downcased_name: "boulevard casino")
Casino.create(name: "Caesars Atlantic City", downcased_name: "caesars atlantic city")
Casino.create(name: "Caesars Las Vegas", downcased_name: "caesars las vegas")
Casino.create(name: "Caesars Windsor", downcased_name: "caesars windsor")
Casino.create(name: "Canterbury Park Card Club", downcased_name: "canterbury park card club")
Casino.create(name: "CardPlayer Cruises", downcased_name: "cardplayer cruises")
Casino.create(name: "Cascades Casino", downcased_name: "cascades casino")
Casino.create(name: "Cash Casino", downcased_name: "cash casino")
Casino.create(name: "Casino at the Empire", downcased_name: "casino at the empire")
Casino.create(name: "Casino Barcelona", downcased_name: "casino barcelona")
Casino.create(name: "Casino Barriere", downcased_name: "casino barriere")
Casino.create(name: "Casino Barrière d'Enghien-les-Bains", downcased_name: "casino barrière d'enghien-les-bains")
Casino.create(name: "Casino Brantford", downcased_name: "casino brantford")
Casino.create(name: "Casino Bregenz - Casinos Austria", downcased_name: "casino bregenz - casinos austria")
Casino.create(name: "Casino Calgary", downcased_name: "casino calgary")
Casino.create(name: "Casino Copenhagen", downcased_name: "casino copenhagen")
Casino.create(name: "Casino de Charlevoix", downcased_name: "casino de charlevoix")
Casino.create(name: "Casino de Lac-Leamy", downcased_name: "casino de lac-leamy")
Casino.create(name: "Casino de Marrakech", downcased_name: "casino de marrakech")
Casino.create(name: "Casino de Montreal", downcased_name: "casino de montreal")
Casino.create(name: "Casino de Mont-Tremblant", downcased_name: "casino de mont-tremblant")
Casino.create(name: "Casino di Campione", downcased_name: "casino di campione")
Casino.create(name: "Casino di Venezia", downcased_name: "casino di venezia")
Casino.create(name: "Casino Edmonton", downcased_name: "casino edmonton")
Casino.create(name: "Casino Gran Madrid", downcased_name: "casino gran madrid")
Casino.create(name: "Casino Lethbridge", downcased_name: "casino lethbridge")
Casino.create(name: "Casino Moosejaw", downcased_name: "casino moosejaw")
Casino.create(name: "Casino Nova Scotia", downcased_name: "casino nova scotia")
Casino.create(name: "Casino Nova Scotia Sydney", downcased_name: "casino nova scotia sydney")
Casino.create(name: "Casino of the Rockies", downcased_name: "casino of the rockies")
Casino.create(name: "Casino Point Edward", downcased_name: "casino point edward")
Casino.create(name: "Casino Rama", downcased_name: "casino rama")
Casino.create(name: "Casino Regina", downcased_name: "casino regina")
Casino.create(name: "Casino Sanremo", downcased_name: "casino sanremo")
Casino.create(name: "Casino Sault Ste. Marie", downcased_name: "casino sault ste. marie")
Casino.create(name: "Casino Seefeld - Casinos Austria", downcased_name: "casino seefeld - casinos austria")
Casino.create(name: "Casino Thousand Islands", downcased_name: "casino thousand islands")
Casino.create(name: "Casino Thunder Bay", downcased_name: "casino thunder bay")
Casino.create(name: "Casino Yellowhead", downcased_name: "casino yellowhead")
Casino.create(name: "Casinos Austria Velden", downcased_name: "casinos austria velden")
Casino.create(name: "Century Casino", downcased_name: "century casino")
Casino.create(name: "Choctaw Casino", downcased_name: "choctaw casino")
Casino.create(name: "City of Dreams Casino - Pokerstars Live", downcased_name: "city of dreams casino - pokerstars live")
Casino.create(name: "City West Hotel", downcased_name: "city west hotel")
Casino.create(name: "Club Regent Casino", downcased_name: "club regent casino")
Casino.create(name: "Commerce Casino", downcased_name: "commerce casino")
Casino.create(name: "Concord Card Casino", downcased_name: "concord card casino")
Casino.create(name: "Crown Casino", downcased_name: "crown casino")
Casino.create(name: "Dakota Dunes Casino", downcased_name: "dakota dunes casino")
Casino.create(name: "Deerfoot Inn & Casino", downcased_name: "deerfoot inn & casino")
Casino.create(name: "Double Tree by Hilton Casino", downcased_name: "double tree by hilton casino")
Casino.create(name: "Dusk Till Dawn", downcased_name: "dusk till dawn")
Casino.create(name: "Elbow River Casino", downcased_name: "elbow river casino")
Casino.create(name: "Foxwoods Casino", downcased_name: "foxwoods casino")
Casino.create(name: "G Casino The Sandcastle", downcased_name: "g casino the sandcastle")
Casino.create(name: "Gold Dust Casino", downcased_name: "gold dust casino")
Casino.create(name: "Gold Eagle Casino", downcased_name: "gold eagle casino")
Casino.create(name: "Gold Strike Casino", downcased_name: "gold strike casino")
Casino.create(name: "Golden Gates Casino", downcased_name: "golden gates casino")
Casino.create(name: "Golden Nugget", downcased_name: "golden nugget")
Casino.create(name: "Golden Prague Poker", downcased_name: "golden prague poker")
Casino.create(name: "Grand Casino Baden", downcased_name: "grand casino baden")
Casino.create(name: "Grand Casino Helsinki", downcased_name: "grand casino helsinki")
Casino.create(name: "Grand Casino Tunica", downcased_name: "grand casino tunica")
Casino.create(name: "Grand Connaught Rooms", downcased_name: "grand connaught rooms")
Casino.create(name: "Grand Hyatt Berlin", downcased_name: "grand hyatt berlin")
Casino.create(name: "Grand Lisboa Casino", downcased_name: "grand lisboa casino")
Casino.create(name: "Grand Sierra Casino", downcased_name: "grand sierra casino")
Casino.create(name: "Grand Waldo Hotel", downcased_name: "grand waldo hotel")
Casino.create(name: "Great Blue Heron Casino", downcased_name: "great blue heron casino")
Casino.create(name: "Great Northern Casino", downcased_name: "great northern casino")
Casino.create(name: "Grey Eagle Casino", downcased_name: "grey eagle casino")
Casino.create(name: "Grosvenor Casino - Luton", downcased_name: "grosvenor casino - luton")
Casino.create(name: "Grosvenor Casino Walsall", downcased_name: "grosvenor casino walsall")
Casino.create(name: "Grosvenor Victoria Casino", downcased_name: "grosvenor victoria casino")
Casino.create(name: "Hard Rock Hotel & Casino Biloxi", downcased_name: "hard rock hotel & casino biloxi")
Casino.create(name: "Hard Rock Hotel & Casino Hollywood", downcased_name: "hard rock hotel & casino hollywood")
Casino.create(name: "Hard Rock Hotel & Casino Las Vegas", downcased_name: "hard rock hotel & casino las vegas")
Casino.create(name: "Hard Rock Hotel & Casino Ohio", downcased_name: "hard rock hotel & casino ohio")
Casino.create(name: "Hard Rock Hotel & Casino Punta Cana", downcased_name: "hard rock hotel & casino punta cana")
Casino.create(name: "Hard Rock Hotel & Casino Seminole", downcased_name: "hard rock hotel & casino seminole")
Casino.create(name: "Hard Rock Hotel & Casino Singaport", downcased_name: "hard rock hotel & casino singaport")
Casino.create(name: "Hard Rock Hotel & Casino Tampa", downcased_name: "hard rock hotel & casino tampa")
Casino.create(name: "Hard Rock Hotel & Casino Tulsa", downcased_name: "hard rock hotel & casino tulsa")
Casino.create(name: "Harrah's Atlantic City", downcased_name: "harrah's atlantic city")
Casino.create(name: "Harrahs Harveys Lake Tahoe Casino", downcased_name: "harrahs harveys lake tahoe casino")
Casino.create(name: "Harrahs Horseshoe Council Bluffs Casino", downcased_name: "harrahs horseshoe council bluffs casino")
Casino.create(name: "Harrah's New Orleans", downcased_name: "harrah's new orleans")
Casino.create(name: "Harrah's Rincon Casino", downcased_name: "harrah's rincon casino")
Casino.create(name: "Harrahs Tunica", downcased_name: "harrahs tunica")
Casino.create(name: "Holland Casino", downcased_name: "holland casino")
Casino.create(name: "Hollywood Casino Lawrenceburg", downcased_name: "hollywood casino lawrenceburg")
Casino.create(name: "Hollywood Park Casino", downcased_name: "hollywood park casino")
Casino.create(name: "Horseshoe Casino", downcased_name: " 	horseshoe casino")
Casino.create(name: "Horseshoe Southern Indiana", downcased_name: "horseshoe southern indiana")
Casino.create(name: "Horseshoe Tunica", downcased_name: "horseshoe tunica")
Casino.create(name: "Hustler Casino", downcased_name: "hustler casino")
Casino.create(name: "IP Hotel & Casino", downcased_name: "ip hotel & casino")
Casino.create(name: "Lake City Casino", downcased_name: "lake city casino")
Casino.create(name: "Le Croisette Casino Barrière Cannes", downcased_name: "le croisette casino barrière cannes")
Casino.create(name: "Living Sky Casino", downcased_name: "living sky casino")
Casino.create(name: "London Clubs International Casino", downcased_name: "london clubs international casino")
Casino.create(name: "Lucky Chances Casino", downcased_name: "lucky chances casino")
Casino.create(name: "Mandalay Bay Resort & Casino", downcased_name: "mandalay bay resort & casino")
Casino.create(name: "Mantra Resort Spa Casino", downcased_name: "mantra resort spa casino")
Casino.create(name: "McPhillips Station Casino", downcased_name: "mcphillips station casino")
Casino.create(name: "Merit Poker Club", downcased_name: " 	merit poker club")
Casino.create(name: "Mirage", downcased_name: " 	mirage")
Casino.create(name: "Mohegan Sun", downcased_name: "mohegan sun")
Casino.create(name: "Moncton Casino New Brunswick", downcased_name: "moncton casino new brunswick")
Casino.create(name: "Monte Carlo Bay Hotel", downcased_name: "monte carlo bay hotel")
Casino.create(name: "Niagara FallsView Casino", downcased_name: "niagara fallsview casino")
Casino.create(name: "Northern Lights Casino", downcased_name: "northern lights casino")
Casino.create(name: "Orleans Hotel & Casino", downcased_name: "orleans hotel & casino")
Casino.create(name: "Palace Casino", downcased_name: "palace casino")
Casino.create(name: "Palm Beach Casino", downcased_name: "palm beach casino")
Casino.create(name: "Palm Beach Kennel Casino", downcased_name: "palm beach kennel casino")
Casino.create(name: "Palms", downcased_name: "palms")
Casino.create(name: "Parx Casino", downcased_name: "parx casino")
Casino.create(name: "Perla Casino & Hotel", downcased_name: "perla casino & hotel")
Casino.create(name: "Playground Poker Club", downcased_name: "playground poker club")
Casino.create(name: "Playground Poker Club Casino", downcased_name: "playground poker club casino")
Casino.create(name: "Pokerstars", downcased_name: "pokerstars")
Casino.create(name: "Radisson Aruba Casino", downcased_name: "radisson aruba casino")
Casino.create(name: "Red Shores Casino", downcased_name: "red shores casino")
Casino.create(name: "Rio ", downcased_name: "rio ")
Casino.create(name: "River Cree Resort & Casino", downcased_name: "river cree resort & casino")
Casino.create(name: "River Rock Casino", downcased_name: "river rock casino")
Casino.create(name: "River Rock Casino Resort", downcased_name: "river rock casino resort")
Casino.create(name: "South Beach Casino", downcased_name: "south beach casino")
Casino.create(name: "Spielbank Hohensyburg", downcased_name: "spielbank hohensyburg")
Casino.create(name: "Stampede Casino", downcased_name: "stampede casino")
Casino.create(name: "Star City Casino", downcased_name: "star city casino")
Casino.create(name: "Starlight Casino", downcased_name: "starlight casino")
Casino.create(name: "Stoney Nakoda Resort & Casino", downcased_name: "stoney nakoda resort & casino")
Casino.create(name: "The Deauville International centre", downcased_name: "the deauville international centre")
Casino.create(name: "The Hilton London Metropole", downcased_name: "the hilton london metropole")
Casino.create(name: "The Isle Casinos", downcased_name: "the isle casino")
Casino.create(name: "Treasure Cove Casino", downcased_name: "treasure cove casino")
Casino.create(name: "Trump Taj Mahal", downcased_name: "trump taj mahal")
Casino.create(name: "Turning Stone Casino", downcased_name: "turning stone casino")
Casino.create(name: "Venetian Casino Resort", downcased_name: "venetian casino resort")
Casino.create(name: "Wild Horse Casino", downcased_name: "wild horse casino")
Casino.create(name: "WinStar Casino", downcased_name: "winstar casino")
Casino.create(name: "Wynn Las Vegas", downcased_name: "wynn las vegas")

Country.create(name: "United States",  photo_name: "flags/United_States_of_America.png")


Country.create(name: "Afghanistan", photo_name: "flags/Afghanistan.png")
Country.create(name: "Albania", photo_name: "flags/Albania.png")
Country.create(name: "Algeria", photo_name: "flags/Algeria.png")
Country.create(name: "American Samoa", photo_name: "flags/American_Samoa.png")
Country.create(name: "Andorra", photo_name: "flags/Andorra.png")
Country.create(name: "Angola", photo_name: "flags/Angola.png")
Country.create(name: "Anguilla", photo_name: "flags/Anguilla.png")
Country.create(name: "Antigua and Barbuda", photo_name: "flags/Antigua_and_Barbuda.png")
Country.create(name: "Argentina", photo_name: "flags/Argentina.png")
Country.create(name: "Armenia", photo_name: "flags/Armenia.png")
Country.create(name: "Aruba", photo_name: "flags/Aruba.png")
Country.create(name: "Australia", photo_name: "flags/Australia.png")
Country.create(name: "Austria", photo_name: "flags/Austria.png")
Country.create(name: "Azerbaijan", photo_name: "flags/Azerbaijan.png")
Country.create(name: "Bahamas", photo_name: "flags/Bahamas.png")
Country.create(name: "Bahrain", photo_name: "flags/Bahrain.png")
Country.create(name: "Bangladesh", photo_name: "flags/Bangladesh.png")
Country.create(name: "Barbados", photo_name: "flags/Barbados.png")
Country.create(name: "Belarus", photo_name: "flags/Belarus.png")
Country.create(name: "Belgium", photo_name: "flags/Belgium.png")
Country.create(name: "Belize", photo_name: "flags/Belize.png")
Country.create(name: "Benin", photo_name: "flags/Benin.png")
Country.create(name: "Bermuda", photo_name: "flags/Bermuda.png")
Country.create(name: "Bhutan", photo_name: "flags/Bhutan.png")
Country.create(name: "Bolivia", photo_name: "flags/Bolivia.png")
Country.create(name: "Bosnia", photo_name: "flags/Bosnia.png")
Country.create(name: "Botswana", photo_name: "flags/Botswana.png")
Country.create(name: "Brazil", photo_name: "flags/Brazil.png")
Country.create(name: "British Virgin Islands", photo_name: "flags/British_Virgin_Islands.png")
Country.create(name: "Brunei", photo_name: "flags/Brunei.png")
Country.create(name: "Bulgaria", photo_name: "flags/Bulgaria.png")
Country.create(name: "Burkina Faso", photo_name: "flags/Burkina_Faso.png")
Country.create(name: "Burundi", photo_name: "flags/Burundi.png")
Country.create(name: "Cambodia", photo_name: "flags/Cambodia.png")
Country.create(name: "Cameroon", photo_name: "flags/Cameroon.png")
Country.create(name: "Canada", photo_name: "flags/Canada.png")
Country.create(name: "Cape Verde", photo_name: "flags/Cape_Verde.png")
Country.create(name: "Cayman Islands", photo_name: "flags/Cayman_Islands.png")
Country.create(name: "Central African Republic", photo_name: "flags/Central_African_Republic.png")
Country.create(name: "Chad", photo_name: "flags/Chad.png")
Country.create(name: "Chile", photo_name: "flags/Chile.png")
Country.create(name: "China", photo_name: "flags/China.png")
Country.create(name: "Christmas Island", photo_name: "flags/Christmas_Island.png")
Country.create(name: "Colombia", photo_name: "flags/Colombia.png")
Country.create(name: "Comoros", photo_name: "flags/Comoros.png")
Country.create(name: "Cook Islands", photo_name: "flags/Cook_Islands.png")
Country.create(name: "Costa Rica", photo_name: "flags/Costa_Rica.png")
Country.create(name: "Croatia", photo_name: "flags/Croatia.png")
Country.create(name: "Cuba", photo_name: "flags/Cuba.png")
Country.create(name: "Cyprus", photo_name: "flags/Cyprus.png")
Country.create(name: "Czech Republic", photo_name: "flags/Czech_Republic.png")
Country.create(name: "Cote d'Ivoire", photo_name: "flags/Cote_d'Ivoire.png")
Country.create(name: "Democratic Republic of the Congo", photo_name: "flags/Democratic_Republic_of_the_Congo.png")
Country.create(name: "Denmark", photo_name: "flags/Denmark.png")
Country.create(name: "Djibouti", photo_name: "flags/Djibouti.png")
Country.create(name: "Dominica", photo_name: "flags/Dominica.png")
Country.create(name: "Dominican Republic", photo_name: "flags/Dominican_Republic.png")
Country.create(name: "Ecuador", photo_name: "flags/Ecuador.png")
Country.create(name: "Egypt", photo_name: "flags/Egypt.png")
Country.create(name: "El Salvador", photo_name: "flags/El_Salvador.png")
Country.create(name: "Equatorial Guinea", photo_name: "flags/Equatorial_Guinea.png")
Country.create(name: "Eritrea", photo_name: "flags/Eritrea.png")
Country.create(name: "Estonia", photo_name: "flags/Estonia.png")
Country.create(name: "Ethiopia", photo_name: "flags/Ethiopia.png")

Country.create(name: "Falkland Islands", photo_name: "flags/Falkland_Islands.png")
Country.create(name: "Faroe Islands", photo_name: "flags/Faroe_Islands.png")
Country.create(name: "Fiji", photo_name: "flags/Fiji.png")
Country.create(name: "Finland", photo_name: "flags/Finland.png")
Country.create(name: "France", photo_name: "flags/France.png")
Country.create(name: "French Polynesia", photo_name: "flags/French_Polynesia.png")
Country.create(name: "Gabon", photo_name: "flags/Gabon.png")
Country.create(name: "Gambia", photo_name: "flags/Gambia.png")
Country.create(name: "Georgia", photo_name: "flags/Georgia.png")
Country.create(name: "Germany", photo_name: "flags/Germany.png")
Country.create(name: "Ghana", photo_name: "flags/Ghana.png")
Country.create(name: "Gibraltar", photo_name: "flags/Gibraltar.png")
Country.create(name: "Greece", photo_name: "flags/Greece.png")
Country.create(name: "Greenland", photo_name: "flags/Greenland.png")
Country.create(name: "Grenada", photo_name: "flags/Grenada.png")
Country.create(name: "Guam", photo_name: "flags/Guam.png")
Country.create(name: "Guatemala", photo_name: "flags/Guatemala.png")
Country.create(name: "Guinea", photo_name: "flags/Guinea.png")
Country.create(name: "Guinea Bissau", photo_name: "flags/Guinea_Bissau.png")
Country.create(name: "Guyana", photo_name: "flags/Guyana.png")
Country.create(name: "Haiti", photo_name: "flags/Haiti.png")
Country.create(name: "Honduras", photo_name: "flags/Honduras.png")
Country.create(name: "Hong Kong", photo_name: "flags/Hong_Kong.png")
Country.create(name: "Hungary", photo_name: "flags/Hungary.png")

Country.create(name: "Iceland", photo_name: "flags/Iceland.png")
Country.create(name: "India", photo_name: "flags/India.png")
Country.create(name: "Indonesia", photo_name: "flags/Indonesia.png")
Country.create(name: "Iran", photo_name: "flags/Iran.png")
Country.create(name: "Iraq", photo_name: "flags/Iraq.png")
Country.create(name: "Ireland", photo_name: "flags/Ireland.png")
Country.create(name: "Israel", photo_name: "flags/Israel.png")
Country.create(name: "Italy", photo_name: "flags/Italy.png")
Country.create(name: "Jamaica", photo_name: "flags/Jamaica.png")
Country.create(name: "Japan", photo_name: "flags/Japan.png")
Country.create(name: "Jordan", photo_name: "flags/Jordan.png")
Country.create(name: "Kazakhstan", photo_name: "flags/Kazakhstan.png")
Country.create(name: "Kenya", photo_name: "flags/Kenya.png")
Country.create(name: "Kiribati", photo_name: "flags/Kiribati.png")
Country.create(name: "Kuwait", photo_name: "flags/Kuwait.png")
Country.create(name: "Kyrgyzstan", photo_name: "flags/Kyrgyzstan.png")
Country.create(name: "Laos", photo_name: "flags/Laos.png")
Country.create(name: "Latvia", photo_name: "flags/Latvia.png")
Country.create(name: "Lebanon", photo_name: "flags/Lebanon.png")
Country.create(name: "Lesotho", photo_name: "flags/Lesotho.png")
Country.create(name: "Liberia", photo_name: "flags/Liberia.png")
Country.create(name: "Libya", photo_name: "flags/Libya.png")
Country.create(name: "Liechtenstein", photo_name: "flags/Liechtenstein.png")
Country.create(name: "Lithuania", photo_name: "flags/Lithuania.png")
Country.create(name: "Luxembourg", photo_name: "flags/Luxembourg.png")
Country.create(name: "Macao", photo_name: "flags/Macao.png")
Country.create(name: "Macedonia", photo_name: "flags/Macedonia.png")
Country.create(name: "Madagascar", photo_name: "flags/Madagascar.png")
Country.create(name: "Malawi", photo_name: "flags/Malawi.png")

Country.create(name: "Malaysia", photo_name: "flags/Malaysia.png")
Country.create(name: "Maldives", photo_name: "flags/Maldives.png")
Country.create(name: "Mali", photo_name: "flags/Mali.png")
Country.create(name: "Malta", photo_name: "flags/Malta.png")
Country.create(name: "Marshall Islands", photo_name: "flags/Marshall_Islands.png")
Country.create(name: "Martinique", photo_name: "flags/Martinique.png")
Country.create(name: "Mauritania", photo_name: "flags/Mauritania.png")
Country.create(name: "Mauritius", photo_name: "flags/Mauritius.png")
Country.create(name: "Mexico", photo_name: "flags/Mexico.png")
Country.create(name: "Micronesia", photo_name: "flags/Micronesia.png")
Country.create(name: "Moldova", photo_name: "flags/Moldova.png")
Country.create(name: "Monaco", photo_name: "flags/Monaco.png")
Country.create(name: "Mongolia", photo_name: "flags/Mongolia.png")
Country.create(name: "Montserrat", photo_name: "flags/Montserrat.png")
Country.create(name: "Morocco", photo_name: "flags/Morocco.png")
Country.create(name: "Mozambique", photo_name: "flags/Mozambique.png")
Country.create(name: "Myanmar", photo_name: "flags/Myanmar.png")
Country.create(name: "Namibia", photo_name: "flags/Namibia.png")
Country.create(name: "Nauru", photo_name: "flags/Nauru.png")
Country.create(name: "Nepal", photo_name: "flags/Nepal.png")
Country.create(name: "Netherlands", photo_name: "flags/Netherlands.png")
Country.create(name: "Netherlands Antilles", photo_name: "flags/Netherlands_Antilles.png")
Country.create(name: "New Zealand", photo_name: "flags/New_Zealand.png")
Country.create(name: "Nicaragua", photo_name: "flags/Nicaragua.png")
Country.create(name: "Niger", photo_name: "flags/Niger.png")
Country.create(name: "Nigeria", photo_name: "flags/Nigeria.png")
Country.create(name: "Niue", photo_name: "flags/Niue.png")
Country.create(name: "Norfolk Island", photo_name: "flags/Norfolk_Island.png")
Country.create(name: "Norway", photo_name: "flags/Norway.png")
Country.create(name: "Oman", photo_name: "flags/Oman.png")
Country.create(name: "Pakistan", photo_name: "flags/Pakistan.png")

Country.create(name: "Palau", photo_name: "flags/Palau.png")
Country.create(name: "Panama", photo_name: "flags/Panama.png")
Country.create(name: "Papua New Guinea", photo_name: "flags/Papua_New_Guinea.png")
Country.create(name: "Paraguay", photo_name: "flags/Paraguay.png")
Country.create(name: "Peru", photo_name: "flags/Peru.png")
Country.create(name: "Philippines", photo_name: "flags/Philippines.png")
Country.create(name: "Pitcairn Islands", photo_name: "flags/Pitcairn_Islands.png")
Country.create(name: "Poland", photo_name: "flags/Poland.png")
Country.create(name: "Portugal", photo_name: "flags/Portugal.png")
Country.create(name: "Puerto Rico", photo_name: "flags/Puerto_Rico.png")
Country.create(name: "Qatar", photo_name: "flags/Qatar.png")
Country.create(name: "Republic of the Congo", photo_name: "flags/Republic_of_the_Congo.png")
Country.create(name: "Romania", photo_name: "flags/Romania.png")
Country.create(name: "Russian Federation", photo_name: "flags/Russian_Federation.png")
Country.create(name: "Rwanda", photo_name: "flags/Rwanda.png")
Country.create(name: "Saint Kitts and Nevis", photo_name: "flags/Saint_Kitts_and_Nevis.png")
Country.create(name: "Saint Lucia", photo_name: "flags/Saint_Lucia.png")
Country.create(name: "Saint Pierre", photo_name: "flags/Saint_Pierre.png")
Country.create(name: "Saint Vicent and the Grenadines", photo_name: "flags/Saint_Vicent_and_the_Grenadines.png")
Country.create(name: "Samoa", photo_name: "flags/Samoa.png")
Country.create(name: "San Marino", photo_name: "flags/San_Marino.png")
Country.create(name: "Sao Tome and Principe", photo_name: "flags/Sao_Tome_and_Principe.png")
Country.create(name: "Saudi Arabia", photo_name: "flags/Saudi_Arabia.png")
Country.create(name: "Senegal", photo_name: "flags/Senegal.png")
Country.create(name: "Serbia and Montenegro", photo_name: "flags/Serbia_and_Montenegro.png")
Country.create(name: "Seychelles", photo_name: "flags/Seychelles.png")
Country.create(name: "Sierra Leone", photo_name: "flags/Sierra_Leone.png")
Country.create(name: "Singapore", photo_name: "flags/Singapore.png")
Country.create(name: "Slovakia", photo_name: "flags/Slovakia.png")
Country.create(name: "Slovenia", photo_name: "flags/Slovenia.png")

Country.create(name: "Soloman Islands", photo_name: "flags/Soloman_Islands.png")
Country.create(name: "Somalia", photo_name: "flags/Somalia.png")
Country.create(name: "South Africa", photo_name: "flags/South_Africa.png")
Country.create(name: "South Georgia", photo_name: "flags/South_Georgia.png")
Country.create(name: "South Korea", photo_name: "flags/South_Korea.png")
Country.create(name: "Spain", photo_name: "flags/Spain.png")
Country.create(name: "Sri Lanka", photo_name: "flags/Sri_Lanka.png")
Country.create(name: "Sudan", photo_name: "flags/Sudan.png")
Country.create(name: "Suriname", photo_name: "flags/Suriname.png")
Country.create(name: "Swaziland", photo_name: "flags/Swaziland.png")

Country.create(name: "Sweden", photo_name: "flags/Sweden.png")
Country.create(name: "Switzerland", photo_name: "flags/Switzerland.png")
Country.create(name: "Syria", photo_name: "flags/Syria.png")
Country.create(name: "Taiwan", photo_name: "flags/Afghanistan.png")
Country.create(name: "Tajikistan", photo_name: "flags/Tajikistan.png")
Country.create(name: "Tanzania", photo_name: "flags/Tanzania.png")
Country.create(name: "Thailand", photo_name: "flags/Thailand.png")
Country.create(name: "Tibet", photo_name: "flags/Tibet.png")
Country.create(name: "Timor-Leste", photo_name: "flags/Timor-Leste.png")
Country.create(name: "Togo", photo_name: "flags/Togo.png")
Country.create(name: "Tonga", photo_name: "flags/Tonga.png")
Country.create(name: "Trinidad and Tobago", photo_name: "flags/Trinidad_and_Tobago.png")
Country.create(name: "Tunisia", photo_name: "flags/Tunisia.png")
Country.create(name: "Turkey", photo_name: "flags/Turkey.png")
Country.create(name: "Turkmenistan", photo_name: "flags/Turkmenistan.png")
Country.create(name: "Turks and Caicos Islands", photo_name: "flags/Turks_and_Caicos_Islands.png")

Country.create(name: "Tuvalu", photo_name: "flags/Tuvalu.png")
Country.create(name: "UAE", photo_name: "flags/UAE.png")
Country.create(name: "Uganda", photo_name: "flags/Uganda.png")
Country.create(name: "Ukraine", photo_name: "flags/Ukraine.png")
Country.create(name: "United Kingdom", photo_name: "flags/United_Kingdom.png")
Country.create(name: "Uruguay", photo_name: "flags/Uruguay.png")
Country.create(name: "US Virgin Islands", photo_name: "flags/US_Virgin_Islands.png")
Country.create(name: "Uzbekistan", photo_name: "flags/Uzbekistan.png")
Country.create(name: "Vanuatu", photo_name: "flags/Vanuatu.png")
Country.create(name: "Vatican City", photo_name: "flags/Vatican_City.png")
Country.create(name: "Venezuela", photo_name: "flags/Venezuela.png")
Country.create(name: "Vietnam", photo_name: "flags/Vietnam.png")
Country.create(name: "Wallis and Futuna", photo_name: "flags/Wallis_and_Futuna.png")
Country.create(name: "Yemen", photo_name: "flags/Yemen.png")
Country.create(name: "Zambia", photo_name: "flags/Zambia.png")
Country.create(name: "Zimbabwe", photo_name: "flags/Zimbabwe.png")
